apiVersion: apps/v1  #Defines the API Version
kind: Deployment     #Kinds parameter defines which kind of file is it, over here it is Deployment
metadata:
  name: bank-provider-api        #Stores the name of the deployment
spec:               # Under Specifications, you mention all the specifications for the deployment
  replicas: 2       # Number of replicas would be 3
  selector:
   matchLabels:
     app: bank-provider-api     #Label name which would be searched is httpd
  template:
    metadata:
      labels:
        app: bank-provider-api   #Template name would be httpd
    spec:            # Under Specifications, you mention all the specifications for the containers
      containers:
      - name: bank-provider-api   #Name of the containers would be httpd
        image: demo-bank-provider:1.0  #The image which has to be downloaded is httpd:latest
        ports:
        - containerPort: 8083 #The application would be exposed on port 8083
