apiVersion: v1  #Defines the API Version
kind: Service   #Kinds parameter defines which kind of file is it, over here it is Service
metadata:
  name: bank-provider-service   #Stores the name of the service
spec:            # Under Specifications, you mention all the specifications for the service
  type: ClusterIP
  selector:
    app: transfer-corebank-provider-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
