server:
  port: 8081
spring:
  rabbitmq:
    host: 192.168.56.103
    port: 5672
    cache:
      channel:
        checkout-timeout: 500
        size: 2048
    listener:
      simple:
        concurrency: 10
        max-concurrency: 100
  jms:
    listener:
      concurrency: 10
      max-concurrency: 100